name: Keep Repository Active

on:
  schedule:
    - cron: '11 0 * * 1'  # 每周一凌晨 0 点执行
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update timestamp
        run: |
          echo "Last update: $(date)" > LAST_UPDATED.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add LAST_UPDATED.txt
          git commit -m "chore: keep repo active" || echo "No changes to commit"
          git push
